/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 20-Jun-2020 17:41:43
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 52
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */


/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
int BL = 52;
const float B[52] = {
   0.008676571772, 0.009030717425,-0.009415003471,-0.009833447635,  0.01029081736,
    0.01079280861, -0.01134628616, -0.01195959933,  0.01264300477,  0.01340924762,
   -0.01427435968, -0.01525879838,  0.01638907939,  0.01770020649, -0.01923935488,
    -0.0210716743,  0.02328974567,  0.02602971531, -0.02950034477, -0.03403886035,
      0.040227741,   0.0491672419, -0.06321502477, -0.08850103617,    0.147501722,
      0.442505151,    0.442505151,    0.147501722, -0.08850103617, -0.06321502477,
     0.0491672419,    0.040227741, -0.03403886035, -0.02950034477,  0.02602971531,
    0.02328974567,  -0.0210716743, -0.01923935488,  0.01770020649,  0.01638907939,
   -0.01525879838, -0.01427435968,  0.01340924762,  0.01264300477, -0.01195959933,
   -0.01134628616,  0.01079280861,  0.01029081736,-0.009833447635,-0.009415003471,
   0.009030717425, 0.008676571772
};
